name: Terraform Deployment
on: 
  pull_request:
    branches:
      - main

permissions:
  id-token: write # Required for requesting the JWT
  contents: read  # Required for actions/checkout
  pull-requests: write # Required for actions/github-script

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/1073687322815/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'terraform-project2@project-55dcf55b-027c-4122-a45.iam.gserviceaccount.com'
          token_format: 'access_token'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.0"
          terraform_wrapper: false

      - name: Terraform Init
        run: cd 02_infra_as_code_with_terraform/gcp &&terraform init

      - name: Terraform format
        id: fmt
        run: cd 02_infra_as_code_with_terraform/gcp && terraform fmt -check

      - name: Create auto.tfvars file
        run: |
          echo 'environment = "${{ secrets.ENVIRONMENT }}"' >> 02_infra_as_code_with_terraform/gcp/terraform.auto.tfvars
          echo 'region = "${{ secrets.REGION }}"' >> 02_infra_as_code_with_terraform/gcp/terraform.auto.tfvars
          echo 'project_id = "${{ secrets.PROJECT_ID }}"' >> 02_infra_as_code_with_terraform/gcp/terraform.auto.tfvars


      - name: Terraform validate
        run: cd 02_infra_as_code_with_terraform/gcp && terraform validate

      - name: Terraform plan
        id: plan
        run: | 
          cd 02_infra_as_code_with_terraform/gcp && terraform plan -no-color> plan_output.txt
          
          # 2. Write the output to the GitHub Step summary and outputs
          echo "stdout<<EOF" >> $GITHUB_OUTPUT
          cat plan_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Prepare the success/failure emojis
            const fmtOutcome = '${{ steps.fmt.outcome }}' === 'success' ? '✅' : '❌';
            const planOutcome = '${{ steps.plan.outcome }}' === 'success' ? '✅' : '❌';
            const plan = `${{ steps.plan.outputs.stdout }}`;
            const trimmedPlan = plan.length > 60000 ? plan.substring(0, 60000) + "\n... (Plan truncated due to length)" : plan;
            
            // 2. Build the body without leading indentation
            const output = `### Terraform CI Report
            #### Format and Style: ${fmtOutcome} \`${{ steps.fmt.outcome }}\`
            #### Terraform Plan: ${planOutcome} \`${{ steps.plan.outcome }}\`
            
            <details>
            <summary>Click to expand full Plan output</summary>
            
            \`\`\`hcl
            ${trimmedPlan}
            \`\`\`
            
            </details>
            
            *Pushed by: @${context.actor}, Action: \`${context.eventName}\`*`;
            
            // 3. Create the comment
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })